{% set name = "jupyterlab-copy-relative-path" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_copy_relative_path-{{ version }}.tar.gz
  sha256: a545ffcc3853c6a141f542a05551e738d55c9ba6338059c76465a04b7cd0ada3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - jupyter-packaging >=0.10.0,<2
  run:
    - python >=3.6
    - jupyterlab ~=3.0

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab_copy_relative_path/package.json"                            # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab_copy_relative_path\\package.json (exit 0) else (exit 1)  # [win]
  requires:
    - pip

about:
  home: https://github.com/yamaton/jupyterlab_copy_relative_path
  summary: Adds 'Copy Relative Path' to a context menu of JupyterLab file browser.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yamaton
